<html>
    <head>
        <script>
            $(document).ready(function(){
                $("p").click(function(){
                    $("#p1").text("Clicaste no texto, meu");
                });
                $("#ajax").click(function(){
                    $.ajax({
                        url:        '/botoes/ajax/',
                        method:      'POST',
                        dataType:   'json',
                        type:       'async',
                        
                        
                        success: function(data) {
                            alert('Pedido OK');
                            $("#p1").text(data);
                        },
                        error: function(xhr, textStatus, errorThrown){
                            $("#p1").text(xhr+ " "+ errorThrown + " " + textStatus);
                            alert('O pedido AJAX falhou');
                        },
                    });
            
                });
            });
        </script>
    </head>
    <body>
        <h1>Página AJAX</h1>
        <a id="ajax">Carrega AJAX</a>
        <p id="p1">Texto porreiro</p>
    </body>
</html>

