<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Formulário de botões</title>

</head>

<body>
<div class="container">
    <h1> CARREGA NOS BOTÕES DETAIL</h1>
    <div class="col-lg-6">
        <div class="row">
            <button type="button" class="btn btn-primary btn-lg ">Item 1</button>
            <button type="button" class="btn btn-primary btn-lg">Item 2</button>
        </div>
        <div class="row">
            <button type="button" class="btn btn-primary btn-lg">Item 3</button>
            <button type="button" class="btn btn-primary btn-lg">Item 4</button>
        </div>
    </div>
    <div class="col-lg-6">
        <?php
            echo "TABELA DE REGISTOS AQUI";
            echo "</br>";
            echo $pedido->getId();
            echo "   ";
            echo $pedido->getTextobotao();
            echo "</br>";
          
        ?>
    </div>
    
</div>

</body>
</html>



