<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Formulário de botões</title>
</head>
 
<body>
    
    <div class="container">
        <h1> CARREGA NOS BOTÕES</h1>
        <div class="col-lg-6">
            <div class="btn-group btn-group-justified">
                <a type="button" class="btn btn-primary btn-lg" href="<?= $this->url('botoes/adiciona'); ?>">Botão 1</a>
                <a type="button" class="btn btn-primary btn-lg" href="<?= $this->url('botoes/adiciona'); ?>">Botão 2</a>
            </div>
        </div>
        <div class="row-content">
            <?= $this->parcial  ?> 
        </div>
    </div>
</body>
</html>



