<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Submit Button</title>

</head>

<body>
<div class="container">

<h1> CARREGA NOS BOTÕES</h1>
 
<div class="row">
    <div class="col-lg-6">
        <a class="btn btn-success btn-block btn-lg" value="Submit Button-1 A" href="<?= $this->url('botoes/add')?>"></a>
    </div>
    <div class="col-lg-6">
        <input type="submit" class="btn btn-success btn-block btn-lg" value="Submit Button-1 B">
    </div>
</div>


 

</div>

</body>
</html>

