<?php

    $title = "Eventos registados";
    $this->headTitle($title);
    //stylesheet e scripts para datepicker
    $this->headLink()->appendStylesheet($this->basePath('css/jquery-ui.min.css'));
    $this->headScript()->appendFile($this->basePath('js/jquery-ui.min.js'));

?>

<h1><?= $this->escapeHtml($title) ?></h1>

<body>
    
<div class="container">
    <div class="col-md-3">
        <input type="text" name="from_date" id="from_date" class="form-control" placeholder="Data Inicio">
    </div>
    <div class="col-md-3">
        <input type="text" name="to_date" id="to_date" class="form-control" placeholder="Data Fim">
    </div>
    <div class="col-md-5">
        <input type="button" name="filtro" id="filter" value="Filtrar" class="btn btn-info"
    </div>
    <div style="clear:both"></div>
    <br />
    <div id="eventos-table">
    <table class="table table-bordered">
        <tr>
            <th>Evento</th>
            <th>Data</th>
            <th>Hora</th>
        </tr>
        <?php foreach ($eventos as $evento):
            $texto = $this->escapeHtml($evento->getTextobotao());
            $datatempo = new DateTime($this->escapeHtml($evento->getEntrada()));
            $data = $datatempo->format('d/m/Y');
            $hora = $datatempo->format('H:i:s');
            ?>
            <tr>
                <td><?= $this->escapeHtml($texto) ?></td>
                <td><?= $this->escapeHtml($data) ?></td>
                <td><?= $this->escapeHtml($hora) ?></td>
            </tr>
        <?php    endforeach; ?>
    </table>
</div>    
</body>
<script>
    $(document).ready(function(){
        $.datepicker.setDefaults({
            dateFormat: "dd-mm-yy"
        });
        $(function() {
            $("#from_date").datepicker();
            $("#to_date").datepicker();
        });
        $('#filter').click(function(){
            var from_date = $("#from_date").val();
            var to_date = $("#to_date").val();
            if (from_date != '' && to_date != '')
            {
                $.ajax({
                    url:'botoes/ajax',
                    method: "POST",
                    data: {from_date: from_date, to_date: to_date},
                    sucess: function(data)
                    {
                        
                    }
                });
            }
        });
    });

</script>