<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Olá Mundo')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.3.1.js'))
        ?>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <!--Cabeçalho da página -->
                <div class="col-md-4">
                    <div class="app-caption">Olá Mundo</div>
                </div>
            </div>
            <br />
            <div class="collapse navbar-collapse">
                <?= $this->navigation('navigation')
                    ->menu()
                    ->setMinDepth(0)
                    ->setMaxDepth(1)
                    ->setUlClass('nav navbar-nav')
                ?>
            </div>
            
            <div class="row">
                <div class="col-md-12">
                    <!-- placeholder de conteúdo --> 
                    <?= $this->navigation('navigation')
                        ->breadcrumbs()
                        ->setMinDepth(0)
                        ->setPartial('partial/breadcrumb') ?>
                    <?= $this->content; ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <hr>
                    <p>&copy; 2018 - <?= date('Y') ?> by Helder Soares. All rights reserved. </p>
                </div>
            </div>
        </div> <!-- container -->
        <?php echo $this->inlineScript() ?>

    </body>
    
</html>
