<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div>LISTA DE ALBUMS DA BIBLIOTECA CHINOOK</div>
    </body>
</html>

<table class="table">
<tr>
    <th>ID</th>
    <th>Artista</th>
    <th>Título</th>
    <th>&nbsp;</th>
</tr>


<?php foreach ($albums as $album) : ?>
    <tr>
        <td><?= $this->escapeHtml($album->id) ?></td>
        <td><?= $this->escapeHtml($album->artista) ?></td>
        <td><?= $this->escapeHtml($album->titulo) ?></td>
    </tr>
<?php endforeach; ?>
</table>
